spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/doan?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: thai1201
    hikari:
      max-lifetime: 30000
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
  level:
    org.hibernate: WARN
    org.springframework.web: WARN